---
title: "Simple Base Graphics"
author: "David Asare Kumi"
date: "June 8, 2019"
output: html_document
---


##Histogram (1 dimensional)

```{r,echo=TRUE,message=FALSE,warning=FALSE}
library(datasets)
data(airquality)
dim(airquality)
str(airquality)
summary(airquality)
table(airquality$Month)
table(airquality$Day)
#Plot histogram
par(mfrow=c(2,2),mar=c(2,2,1,1))
hist(airquality$Ozone,col="yellow")
hist(airquality$Solar.R,col="green")
hist(airquality$Wind,col="red")
hist(airquality$Temp,col="grey")

```

##Scatterplot

```{r,echo=TRUE,message=FALSE,warning=FALSE}
library(datasets)
data(airquality)
with(airquality,plot(Wind,Ozone,xlab="Wind",ylab="Ozone",col="red",main="Scatterplot of Wind and Ozone",cex=2,pch=20))
#Alternative approach
plot(airquality$Wind,airquality$Ozone,data=airquality,cex=2,pch=20,col="blue",
     main="Scatterplot of Wind and Ozone")

```

##Boxplot(multiple boxplot)

```{r,echo=TRUE,message=FALSE,warning=FALSE}
library(datasets)
data(airquality)
airquality$Month<-as.factor(airquality$Month)
boxplot(Ozone~Month,data=airquality,xlab="Month",ylab="Ozone",main="Boxplot of Ozone on MOnth",col="yellow")

```

##Density plots

```{r,echo=TRUE,message=FALSE,warning=FALSE,fig.height=4}
library(datasets)
data(airquality)
#Plot densities
par(mfrow=c(1,2),mar=c(2,2,1,1))
plot(density(airquality$Wind),col="red",lwd=2,lty=2)
plot(density(airquality$Temp),col="red",lwd=1,lty=1)

```

##Base Plotting System (part2)

###Base Plot with Annotation

```{r,echo=TRUE,message=FALSE,warning=FALSE}
library(datasets)
data(airquality)
with(airquality,plot(Wind,Ozone,main="Ozone and Wind in New York City",cex=1,pch=20))
with(subset(airquality,airquality$Month==5),points(Wind,Ozone,col="blue"))
with(subset(airquality,airquality$Month!=5),points(Wind,Ozone,col="red"))
legend("topright",pch=20,col=c("blue","red"),legend=c("May","OtherMonths"))

```

##Base Plot with Regression Line

```{r,echo=TRUE,message=FALSE,warning=FALSE}
library(datasets)
data(airquality)
with(airquality,plot(Wind,Ozone,main="Ozone and Wind in New York City",pch=20,cex=2,col="red"))
fit<-lm(Ozone~Wind,data=airquality)
abline(fit,lwd=2,lty=2,col="blue")

```

##Multiple Base Plots

```{r,echo=TRUE,message=FALSE,warning=FALSE,fig.height=4}
library(datasets)
data(airquality)
par(mfrow=c(1,2),mar=c(4,4,2,1))
with(airquality,{
  plot(Wind,Ozone,main="Ozone and Wind",cex=1,pch=20,col="red")
  fit1<-lm(Ozone~Wind,data=airquality)
  abline(fit1,lwd=3,lty=1,col="blue")
  plot(Solar.R,Ozone,main="Ozone and Solar Radiation",cex=1,pch=20,col="blue")
  fit2<-lm(Ozone~Solar.R,data=airquality)
  abline(fit2,lwd=2,lty=2,col="red")
})

#Another Example
par(mfrow=c(1,3),mar=c(4,4,2,1),oma=c(0,0,2,0))
with(airquality,{
  plot(Wind,Ozone,main="Ozone and Wind",cex=1,pch=20,col="red")
  fit1<-lm(Ozone~Wind,data=airquality)
  abline(fit1,lwd=3,lty=1,col="blue")
  plot(Solar.R,Ozone,main="Ozone and Solar Radiation",cex=1,pch=20,col="blue")
  fit2<-lm(Ozone~Solar.R,data=airquality)
  abline(fit2,lwd=2,lty=2,col="red")
  plot(Temp,Ozone,main="Ozone and Temperature",cex=1,pch=20,col="green")
  fit3<-lm(Ozone~Temp,data=airquality)
  abline(fit3,lwd=2,lty=2,col="black")
  mtext("Ozone and Weather in New York City",outer=TRUE)
})

```

##Regression Estimates

```{r,echo=TRUE,message=FALSE,warning=FALSE}
library(datasets)
data(airquality)
fit1<-lm(Ozone~Wind,data=airquality)
summary(fit1)$coef
fit2<-lm(Ozone~Solar.R,data=airquality)
summary(fit2)$coef
fit3<-lm(Ozone~Temp,data=airquality)
summary(fit3)$coef

```

##Analysis of Variance

```{r,echo=TRUE,message=FALSE,warning=FALSE}
library(datasets)
data(airquality)
fit1<-lm(Ozone~Wind,data=airquality)
anova(fit1)
fit2<-lm(Ozone~Solar.R,data=airquality)
anova(fit2)
fit3<-lm(Ozone~Temp,data=airquality)
anova(fit3)

```

##Base Plotting Demonstration

```{r,echo=TRUE,message=FALSE,warning=FALSE}
x <-rnorm(100)
y <-rnorm(100)
hist(x,col="yellow")
abline(v=mean(x),lwd=3,lty=2,col="red")
plot(density(x),lwd=3,lty=1,col="red")
abline(v=mean(x),lwd=3,lty=2,col="blue")
plot(x,y,cex=1,pch=20,col="red")
plot(x,y,type="l")

```

##Plotting Symbols

```{r,echo=TRUE,message=FALSE,warning=FALSE}
x <-rnorm(100)
y <-rnorm(100)
plot(x,y,cex=1,pch=20,col="red")
#Plot symbol is a triangle(pch=2)
plot(x,y,cex=1,pch=2,col="red")
#Plot symbol is a plus(pch=3)
plot(x,y,cex=1,pch=3,col="red")
#Plot symbol is a multiplication sign(pch=4)
plot(x,y,cex=1,pch=4,col="red")

```

##Adding title,text,legend etc to plots

```{r,echo=TRUE,message=FALSE,warning=FALSE,fig.width=5}
x <-rnorm(100)
y <-rnorm(100)
plot(x,y,cex=1,pch=20,col="blue")
#Fit a regression line
fit <-lm(y~x)
abline(fit,lwd=2,lty=2,col="red")
#Add a title
title("Scatterplot")
#Add a text
text(-2,-2,"Label")
#Add a legend
legend("topright",legend="Data",pch=20)

```

